-- MySQL Script generated by MySQL Workbench
-- Wed Nov 10 18:51:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `dinnerboss` DEFAULT CHARACTER SET utf8;
USE `dinnerboss` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Empresario(
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL,
  `foto` MEDIUMBLOB NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Telefone (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Estabelecimento (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(18) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `foto` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `mydb`.`Telefone_Empresario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Telefone_Empresario (
  telefone_id INT NOT NULL,
  empresario_id INT NOT NULL,
    FOREIGN KEY (empresario_id)
    REFERENCES Empresario (id),
    FOREIGN KEY (telefone_id)
    REFERENCES Telefone (id));


-- -----------------------------------------------------
-- Table `mydb`.`Telefone_Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Telefone_Estabelecimento (
  `telefone_id` INT NOT NULL,
  `estabelecimento_id` INT NOT NULL,
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES Estabelecimento (`id`),
    FOREIGN KEY (`telefone_id`)
    REFERENCES Telefone (`id`));

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Endereco (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(9) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `estabelecimento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES Estabelecimento (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cardapio (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estabelecimento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES Estabelecimento (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Produto (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `cardapio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`cardapio_id`)
    REFERENCES Cardapio (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Mesa (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade_cadeiras` INT NOT NULL,
  `estabelecimento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES Estabelecimento (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cliente (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL,
  `foto` MEDIUMBLOB NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Avaliacao (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sugestao` VARCHAR(100) NOT NULL,
  `data` DATETIME NOT NULL,
  `estrela` INT NOT NULL,
  `data_horario_avaliacao` TIMESTAMP NOT NULL,
  `estabelecimento_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`estabelecimento_id`)
    REFERENCES Estabelecimento (`id`),
    FOREIGN KEY (`cliente_id`)
    REFERENCES Cliente (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Telefone_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Telefone_Cliente (
  `telefone_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
    FOREIGN KEY (`cliente_id`)
    REFERENCES Cliente (`id`),
    FOREIGN KEY (`telefone_id`)
    REFERENCES Telefone (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Reserva (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora_reservada` DATETIME NOT NULL,
  `data_horario_feito_reserva` TIMESTAMP NOT NULL,
  `cliente_id` INT NOT NULL,
  `mesa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`cliente_id`)
    REFERENCES Cliente (`id`),
    FOREIGN KEY (`mesa_id`)
    REFERENCES Mesa (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
